In [1]:
import pandas as pd
import mysql
from connect import DatabaseConnector

In [2]:
def get_table_data(table_name):
    
    """Prints a summary of the database including number of tables and their columns to an HTML file."""
    db_connector = DatabaseConnector()  # Create an instance of DatabaseConnector

    # Connect to the database
    db_connector.connect_db()

    # Get the database connection
    connection = db_connector.get_connection()

    # If connection is not established, return
    if connection is None:
        print("No connection available to summarize the database.")
        return
    
    cursor = connection.cursor()

    try:
        # Execute the query to fetch the entire table
        cursor.execute(f"SELECT * FROM {table_name}")
        rows = cursor.fetchall()

        # Get column names
        column_names = [i[0] for i in cursor.description]

        # Create a DataFrame from the fetched data
        df = pd.DataFrame(rows, columns=column_names)
        
        return df
    except mysql.connector.Error as e:
        print(f"Error: {e}")
        return None
    finally:
        cursor.close()
        db_connector.close_connection()

In [3]:
df = get_table_data("product_view_logs")

Successfully connected to the database
Connection closed

In [4]:
df.head(10)

,id,user_id,product_id,user_lat,user_long,phone_metadata,user_phone_number,created_at,updated_at
0,1,292,851,NaN,NaN,None,+237651865148,2021-10-28 08:34:25,2021-10-28 08:34:25
1,2,292,552,NaN,NaN,None,+237651865148,2021-10-28 08:34:43,2021-10-28 08:34:43
2,3,292,914,NaN,NaN,None,+237651865148,2021-10-28 08:42:03,2021-10-28 08:42:03
3,4,292,287,NaN,NaN,None,+237651865148,2021-10-28 08:42:22,2021-10-28 08:42:22
4,5,292,182,NaN,NaN,None,+237651865148,2021-10-28 08:42:36,2021-10-28 08:42:36
5,6,292,183,NaN,NaN,None,+237651865148,2021-10-28 08:42:44,2021-10-28 08:42:44
6,7,292,286,NaN,NaN,None,+237651865148,2021-10-28 08:42:58,2021-10-28 08:42:58
7,8,292,42,NaN,NaN,None,+237651865148,2021-10-28 08:43:07,2021-10-28 08:43:07
8,9,292,287,NaN,NaN,None,+237651865148,2021-10-28 08:43:15,2021-10-28 08:43:15
9,10,292,182,NaN,NaN,None,+237651865148,2021-10-28 08:44:10,2021-10-28 08:44:10

In [5]:
def get_tables_and_columns():
    """Fetches all tables and their columns from the database."""

    db_connector = DatabaseConnector()  # Create an instance of DatabaseConnector

    # Connect to the database
    db_connector.connect_db()

    # Get the database connection
    connection = db_connector.get_connection()


    
    if connection is None:
        print("No connection available to fetch data.")
        return None

    cursor = connection.cursor(dictionary=True)

    try:
        tables_info = []

        # Fetch all table names
        cursor.execute("SHOW TABLES")
        tables = cursor.fetchall()

        for table in tables:
            table_name = table[f"Tables_in_{connection.database}"]
            cursor.execute(f"SHOW COLUMNS FROM {table_name}")
            columns = cursor.fetchall()
            tables_info.append({"table_name": table_name, "columns": [column['Field'] for column in columns]})

        return tables_info
    except mysql.connector.Error as e:
        print(f"Error: {e}")
        return None
    finally:
        cursor.close()
        db_connector.close_connection()

In [6]:


tables_info = get_tables_and_columns()

# Print the tables and their columns
for table_info in tables_info:
    print(f"Table: {table_info['table_name']}")
    print(f"Columns: {', '.join(table_info['columns'])}")
    print()

Successfully connected to the database
Connection closed
Table: announcements
Columns: id, title, title_fr, cover_image, video_link, description, description_fr, admin_id, status, publication_date, created_at, updated_at

Table: attribute_values
Columns: id, name, value, product_attribute_id, created_at, updated_at

Table: attributes
Columns: id, name, name_fr, created_at, updated_at

Table: banners
Columns: id, image, vendor_id, created_at, updated_at

Table: brands
Columns: id, name, image, category_id, created_at, updated_at

Table: buy_logs
Columns: id, user_id, product_id, button_type, user_lat, user_long, phone_metadata, user_phone_number, created_at, updated_at

Table: c_r_m_s
Columns: id, title, vendor_id, admin_id, comment, created_at, updated_at

Table: categories
Columns: id, name, image, category_id, name_fr, created_at, updated_at

Table: category_view_logs
Columns: id, user_id, category_id, user_lat, user_long, phone_metadata, user_phone_number, created_at, updated_at

Table: countries
Columns: id, name, iso, code, currency, created_at, updated_at, domain

Table: documents
Columns: id, user_id, type, path, created_at, updated_at

Table: failed_jobs
Columns: id, uuid, connection, queue, payload, exception, failed_at

Table: faqs
Columns: id, question, answer, created_at, updated_at

Table: locations
Columns: id, name, latitude, longitude, radius, created_at, updated_at, country_id

Table: migrations
Columns: id, migration, batch

Table: news_sub_categories
Columns: id, created_at, updated_at

Table: notifications
Columns: id, type, notifiable_type, notifiable_id, data, read_at, created_at, updated_at

Table: oauth_access_tokens
Columns: id, user_id, client_id, name, scopes, revoked, created_at, updated_at, expires_at

Table: oauth_auth_codes
Columns: id, user_id, client_id, scopes, revoked, expires_at

Table: oauth_clients
Columns: id, user_id, name, secret, provider, redirect, personal_access_client, password_client, revoked, created_at, updated_at

Table: oauth_personal_access_clients
Columns: id, client_id, created_at, updated_at

Table: oauth_refresh_tokens
Columns: id, access_token_id, revoked, expires_at

Table: pages
Columns: id, title, title_fr, type, content, content_fr, created_at, updated_at

Table: password_resets
Columns: email, token, created_at

Table: permissions
Columns: id, name, name_fr, slug, created_at, updated_at

Table: product_attribute_values
Columns: id, product_attribute_id, value_id, created_at, updated_at

Table: product_attributes
Columns: id, product_id, attribute_id, created_at, updated_at

Table: product_images
Columns: id, product_id, image, image_original, image_thumb, image_medium, created_at, updated_at

Table: product_view_logs
Columns: id, user_id, product_id, user_lat, user_long, phone_metadata, user_phone_number, created_at, updated_at

Table: product_whole_sales
Columns: id, product_id, quantity, price, created_at, updated_at

Table: products
Columns: id, user_id, name, name_fr, category_id, currency, price, hash, image, image_original, image_thumb, image_medium, description, description_fr, search_index, country, latitude, longitude, brand_id, created_at, updated_at, whole_sale, deleted_at, sellam_id

Table: promotions
Columns: id, title, title_fr, description, description_fr, image, image_thumb, image_medium, product_id, vendor_id, latitude, longitude, start_date, end_date, status, payment_plan, created_at, updated_at

Table: registered_user_tokens
Columns: id, user_id, token, created_at, updated_at

Table: reviews
Columns: id, score, message, user_id, vendor_id, status, created_at, updated_at

Table: role_permissions
Columns: id, role_id, permissions_id, updated_at, created_at

Table: roles
Columns: id, name, name_fr, slug, created_at, updated_at

Table: search_logs
Columns: id, user_id, keyword, number_of_results, user_lat, user_long, phone_metadata, user_phone_number, created_at, updated_at

Table: sellam_category_views
Columns: id, user_id, category_id, user_lat, user_long, phone_metadata, user_phone_number, created_at, updated_at

Table: sellam_orders
Columns: id, sellam_product_id, product_id, user_id, price, delivery_fee, status, payment_method, recipient_name, recipient_phone, recipient_address, city, quantity, created_at, updated_at, payment_status, reference

Table: sellam_product_views
Columns: id, user_id, product_id, button_type, user_lat, user_long, phone_metadata, user_phone_number, created_at, updated_at

Table: sellam_products
Columns: id, product_id, user_id, name, name_fr, category_id, currency, price, hash, image, image_thumb, image_original, image_medium, description, description_fr, search_index, sellam_price, buyam_price, status, brand_id, country, latitude, longitude, whole_sale, created_at, updated_at

Table: subscriptions
Columns: id, name, duration, amount, status, type, created_at, updated_at

Table: templates
Columns: id, name, image, path, status, created_at, updated_at

Table: user_invites
Columns: id, user_id, name, phone, email, status, data, language, message, created_at, updated_at

Table: user_permissions
Columns: id, user_id, permission_id, created_at, updated_at

Table: user_requests
Columns: id, type, image, user_id, description, latitude, longitude, status, created_at, updated_at

Table: user_roles
Columns: id, user_id, role_id, updated_at, created_at

Table: user_subscriptions
Columns: id, subscription_id, vendor_id, duration, amount, payment_method, status, phone_number, account_name, transaction_id, reference, created_at, updated_at, start_date, end_date

Table: users
Columns: id, name, address, email, country, phone, image, image_thumb, image_medium, latitude, longitude, fire_base_token, imei, password, type, status, bio, bio_fr, email_verified_at, search_index, remember_token, created_at, updated_at, approved_at, approved_by, vendor_profile_stage

Table: vendor_Product_views
Columns: product_id, product_id_count

Table: vendor_notification_logs
Columns: id, title, title_fr, message, message_fr, created_at, updated_at

Table: vendor_notifications
Columns: id, user_id, title, title_fr, message, message_fr, type, status, action, content, language, published_date, created_at, updated_at

Table: vendor_of_the_days
Columns: id, vendor_id, date, created_at, updated_at

Table: vendor_ratings
Columns: id, vendor_id, total_rating_count, total_rating_value, total_average_rating, average_rating, weighted_rating, created_at, updated_at

Table: vendor_search_logs
Columns: id, user_id, search_term, created_at, updated_at, total

Table: vendor_view_logs
Columns: id, user_id, vendor_id, user_lat, user_long, phone_metadata, user_phone_number, created_at, updated_at

Table: vendors
Columns: id, user_id, type, name, address, created_at, updated_at, subdomain, template_id, about, logo, facebook, twitter, instagram, linkedin, approved_at, managed_by_admin

Table: wishlists
Columns: id, user_id, product_id, category_id, created_at, updated_at

In [7]:
df = get_table_data("vendor_view_logs")

Successfully connected to the database
Connection closed

In [8]:
df.head(10)

,id,user_id,vendor_id,user_lat,user_long,phone_metadata,user_phone_number,created_at,updated_at
0,1,292,2561,0.000000,0.000000,None,+237651865148,2021-10-28 08:41:43,2021-10-28 08:41:43
1,2,115,26,0.000000,0.000000,None,237650628474,2021-10-28 09:34:06,2021-10-28 09:34:06
2,3,0,268,3.848000,11.502100,None,,2021-10-28 10:38:00,2021-10-28 10:38:00
3,4,0,266,4.160232,9.282543,None,,2021-10-28 11:08:04,2021-10-28 11:08:04
4,5,0,268,4.160552,9.282196,None,,2021-10-28 11:13:38,2021-10-28 11:13:38
5,6,0,2252,NaN,NaN,None,,2021-10-28 11:25:14,2021-10-28 11:25:14
6,7,0,2785,4.159316,9.279771,None,,2021-10-28 12:56:08,2021-10-28 12:56:08
7,8,0,2459,0.000000,0.000000,None,,2021-10-28 13:03:39,2021-10-28 13:03:39
8,9,0,2491,0.000000,0.000000,None,,2021-10-28 13:04:01,2021-10-28 13:04:01
9,10,0,2785,0.000000,0.000000,None,,2021-10-28 13:04:47,2021-10-28 13:04:47

In [9]:
df = get_table_data("categories")

Successfully connected to the database
Connection closed

In [10]:
df.head(50)

,id,name,image,category_id,name_fr,created_at,updated_at
0,6,Electronics,60c8c9a4024dc.png,0,Électronique\r\n,2021-06-08 10:44:42,2021-06-15 19:39:16
1,7,Mobile Phones,61a9283fb109b.png,23,Téléphones portables,2021-06-08 10:44:42,2021-12-03 01:10:39
2,8,Computers,60c8e0f87536f.png,24,Informatique\r\n,2021-06-08 10:44:42,2021-06-16 23:45:11
3,15,Home & Kitchen,60e309bc57837.png,22,Maison & Cuisine,2021-06-08 10:44:42,2021-07-05 17:31:40
4,17,Home & Office Furniture,60e30a3ad0b2f.png,22,furniture,2021-06-08 10:44:42,2021-07-05 17:33:46
5,18,Table,60e31631d231e.png,17,Table,2021-06-08 10:44:42,2021-07-05 18:24:49
6,19,Bed,60e3179988feb.png,17,Lit,2021-06-08 10:44:42,2021-07-05 18:30:49
7,20,Super Market,60de4d42cdf92.png,0,Supermarché,2021-06-15 14:36:43,2021-07-02 03:18:26
8,21,Health & Beauty,61a9252413869.png,0,Beauté & Hygiène\r\n,2021-06-15 14:36:43,2021-12-03 00:57:24
9,22,Home & Office,60e30913071e5.png,0,Maison et Bureau,2021-06-15 14:36:43,2021-07-05 17:28:51
10,23,Phone & Tablets,61a926e8eb3cf.png,0,Téléphone et tablettes,2021-06-15 14:36:43,2021-12-03 01:04:56
11,24,Computing,60c8d1fc9d0c1.png,0,Informatique,2021-06-15 14:36:43,2021-06-15 20:14:52
12,27,Baby Products,60c8d33f5a41b.png,0,Produits pour bébés,2021-06-15 14:36:43,2021-06-15 20:20:15
13,28,Gaming,60c8d264caaf3.png,0,Jeu,2021-06-15 14:36:43,2021-06-15 20:16:36
14,29,Sporting Goods,60c8d2c9d0733.png,0,Articles de sport,2021-06-15 14:36:43,2021-06-15 20:18:17
15,30,Automobiles,60de4dedecc26.png,0,Automobiles,2021-06-15 14:36:43,2021-07-02 03:21:17
16,31,Real Estate,60de537e1f8e7.png,0,Immobilier,2021-06-15 14:36:43,2021-07-02 03:45:02
17,32,Other Categories,60c8d6290b5aa.png,0,\t\r\nAutres catégories,2021-06-15 14:36:43,2021-06-15 20:32:41
18,43,Home Audio,61a1123e32c41.png,6,\t\r\nAudio à domicile,2021-06-15 21:08:38,2021-11-26 21:58:38
19,45,Camera and Photo,616dc010ae3a5.png,6,\t\r\nAppareil photo et photo,2021-06-15 21:08:38,2021-10-18 22:42:24
20,47,Generator and Portable Power,61a112e0b7860.png,6,\t\r\nGénérateur et alimentation portable\r\n,2021-06-15 21:08:38,2021-11-26 22:01:20
21,48,Food Cupboard,61a1277d664c1.png,20,\t\r\nPlacard alimentaire\r\n,2021-06-15 21:12:58,2021-11-26 23:29:17
22,49,Household cleaning,61a128114238d.png,20,\t\r\nNettoyage ménager\r\n,2021-06-15 21:12:58,2021-11-26 23:31:45
23,50,"Beer, wine and spirits",61a128871009d.png,20,"\t\r\nBière, vin et spiritueux\r\n",2021-06-15 21:12:58,2021-11-26 23:33:43
24,51,Make up,6128dba18a951.png,21,\t\r\nMaquillage\r\n,2021-06-15 21:14:34,2021-08-27 16:33:37
25,52,Hair care,6128ccfc491c9.png,21,Soins des cheveux\r\n,2021-06-15 21:14:34,2021-08-27 15:31:08
26,53,Health Care,61a9209370b3d.png,21,Soins de santé\r\n,2021-06-15 21:14:34,2021-12-03 00:37:55
27,54,Personal Care,61a91db37478f.png,21,Soins personnels\r\n,2021-06-15 21:14:34,2021-12-03 00:25:39
28,55,Oral Care,631f17bcbef1a.png,21,Soins bucco-dentaires\r\n,2021-06-15 21:14:34,2022-09-12 11:27:56
29,56,Fragrances,61a91f8857ac3.png,21,Parfums\r\n,2021-06-15 21:14:34,2021-12-03 00:33:28
30,57,Large Appliances,60c8d09d34545.png,22,Gros appareils électroménagers,2021-06-15 21:15:31,2021-06-15 21:15:31
31,58,Small Appliances,60c8d09d34545.png,22,Petits appareils électroménagers,2021-06-15 21:15:31,2021-06-15 21:16:17
32,59,Office Products,60c8d09d34545.png,22,Produits de bureau,2021-06-15 21:15:53,2021-06-15 21:15:53
33,60,Tablets,61a928b966c6d.png,23,Tablettes,2021-06-15 21:17:58,2021-12-03 01:12:41
34,61,Smart Phones,61a92a3ecfc94.png,7,Smart Phones,2021-06-15 21:17:58,2021-12-03 01:19:10
35,62,Mobile Accessories,61a929f4d40c5.png,23,Accessoires mobiles,2021-06-15 21:17:58,2021-12-03 01:17:56
36,63,Printers,60c8d1fc9d0c1.png,24,Imprimantes,2021-06-15 21:20:05,2021-06-16 23:37:01
37,64,Computer Accessories,60c8d1fc9d0c1.png,24,Accessoires pour ordinateurs,2021-06-15 21:20:05,2021-06-15 21:20:05
38,65,Data Storage,60c8d1fc9d0c1.png,24,Stockage des données,2021-06-15 21:20:05,2021-06-15 21:20:05
39,66,Network Accessories,60c8d1fc9d0c1.png,24,Accessoires de réseau\r\n,2021-06-15 21:20:05,2021-06-15 21:20:05
40,67,Feeding,60c8d33f5a41b.png,27,Alimentation\r\n,2021-06-15 21:21:22,2021-06-15 21:21:22
41,68,Gear,60c8d33f5a41b.png,27,Engrenage\r\n,2021-06-15 21:21:22,2021-06-15 21:21:22
42,69,Baby and Toddler Toys,60c8d33f5a41b.png,27,Jouets pour bébés et jeunes enfants\r\n,2021-06-15 21:21:22,2021-06-15 21:21:22
43,70,Diapering,60c8d33f5a41b.png,27,Changements de couches\r\n,2021-06-15 21:21:22,2021-06-15 21:21:22
44,71,Play Station,60c8d264caaf3.png,28,Station de jeu\r\n,2021-06-15 21:22:11,2021-06-15 21:22:11
45,72,Nintendo,60c8d264caaf3.png,28,Nintendo\r\n,2021-06-15 21:22:11,2021-06-15 21:22:11
46,73,XBOX,60c8d264caaf3.png,28,XBOX\r\n,2021-06-15 21:22:11,2021-06-15 21:22:11
47,74,Top Games,60c8d264caaf3.png,28,Top Jeux\r\n,2021-06-15 21:22:11,2021-06-15 21:22:11
48,75,Cardio Training,60c8d2c9d0733.png,29,Cardio Training,2021-06-15 21:23:37,2021-06-15 21:23:37
49,76,Team Sports,60c8d2c9d0733.png,29,Sports d'équipe\r\n,2021-06-15 21:23:37,2021-06-15 21:23:37

In [11]:
def get_vendor_rank(vendor_id):
    db_connector = DatabaseConnector()  # Create an instance of DatabaseConnector
    # Connect to the database
    db_connector.connect_db()
    # Get the database connection
    connection = db_connector.get_connection()

    # If connection is not established, return
    if connection is None:
        print("No connection available to retrieve vendor ranks.")
        return

    cursor = connection.cursor()

    try:
        # Execute the query to calculate the total count of views for each vendor
        query = """
            SELECT vendor_id, COUNT(*) AS total_views
            FROM vendor_view_logs
            GROUP BY vendor_id
        """
        cursor.execute(query)
        results = cursor.fetchall()

        # Sort results by total views in descending order
        sorted_results = sorted(results, key=lambda x: x[1], reverse=True)

        # Find rank of the specified vendor
        rank = next((i+1 for i, (v_id, _) in enumerate(sorted_results) if v_id == vendor_id), None)

        return rank

    except mysql.connector.Error as e:
        print(f"Error: {e}")
    finally:
        cursor.close()
        db_connector.close_connection()

In [12]:
# Example usage
vendor_id = 266  # Replace with the actual vendor ID
rank = get_vendor_rank(vendor_id)
if rank is not None:
    print(f"Rank of vendor {vendor_id} based on total views: {rank}")
else:
    print("Vendor not found or error occurred.")

Successfully connected to the database
Connection closed
Rank of vendor 266 based on total views: 54

In [14]:
df1 = get_table_data("buy_logs")
df2 = get_table_data("vendors")
df3 = get_table_data("products")

Successfully connected to the database
Connection closed
Successfully connected to the database
Connection closed
Successfully connected to the database
Connection closed

In [15]:
df1.head(10)

,id,user_id,product_id,button_type,user_lat,user_long,phone_metadata,user_phone_number,created_at,updated_at
0,1,0,642,WhatsApp,51.507198,-0.1275,LGE Nexus 5X,,2021-10-29 17:30:03,2021-10-29 17:30:03
1,2,0,641,WhatsApp,51.507198,-0.1275,LGE Nexus 5X,,2021-10-29 17:30:42,2021-10-29 17:30:42
2,3,0,641,WhatsApp,51.507198,-0.1275,LGE Nexus 5X,,2021-10-29 17:30:44,2021-10-29 17:30:44
3,4,0,707,WhatsApp,41.836899,-87.6847,LGE Nexus 5X,,2021-10-29 17:33:45,2021-10-29 17:33:45
4,5,0,705,WhatsApp,41.836899,-87.6847,LGE Nexus 5X,,2021-10-29 17:34:00,2021-10-29 17:34:00
5,6,0,933,WhatsApp,41.836899,-87.6847,LGE Nexus 5X,,2021-10-29 17:35:48,2021-10-29 17:35:48
6,7,0,835,WhatsApp,41.836899,-87.6847,LGE Nexus 5X,,2021-10-29 17:38:31,2021-10-29 17:38:31
7,8,0,711,WhatsApp,41.836899,-87.6847,LGE Nexus 5X,,2021-10-29 17:38:50,2021-10-29 17:38:50
8,9,2820,597,WhatsApp,0.000000,0.0000,TECNO MOBILE LIMITED TECNO CD7,237670389828,2021-10-31 11:58:11,2021-10-31 11:58:11
9,10,1672,949,WhatsApp,0.000000,0.0000,Samsung SM-G935S,237676694222,2021-10-31 14:45:46,2021-10-31 14:45:46

In [16]:
df2.head(10)

,id,user_id,type,name,address,created_at,updated_at,subdomain,template_id,about,logo,facebook,twitter,instagram,linkedin,approved_at,managed_by_admin
0,20,26,business,Hitech Cameroon Sarl,Casino Bastos,2021-06-10 10:24:20,2024-06-13 06:37:43,andin-654453144.buyam.cm,5.0,None,60cc85dbbcc49.png,https://www.facebook.com/hitechcm/,None,https://www.instagram.com/hitechcameroon/?hl=en,None,None,0
1,23,39,business,CGI CAMEROUN SA,"576 Route de MELEN, BP 30181 YAOUNDE",2021-06-14 20:23:25,2022-06-15 16:39:27,cgi.buyam.cm,NaN,None,None,None,None,None,None,None,0
2,25,44,individual,Hot Sauce,Bunduma Gate,2021-06-16 15:18:34,2024-04-06 17:01:31,672627247.buyam.cm,2.0,text,60cc74c2c70d0.png,text,None,text,None,None,0
3,26,45,business,Njorku Store,"UB Junction, Molyko, Buea",2021-06-16 15:35:23,2022-06-15 16:39:27,njorku-store.buyam.cm,NaN,None,None,None,None,None,None,None,0
4,27,42,business,Tour Jumelle,"Douala, Kotto...Mbangue ,Toiture Rouge",2021-06-16 15:49:45,2022-06-15 16:39:27,tourjumelle.buyam.cm,NaN,None,None,None,None,None,None,None,0
5,28,50,business,Lawal Center,"Avenue Kennedy, face maison orange",2021-06-16 18:38:43,2022-06-15 16:39:27,lawal-center.buyam.cm,NaN,None,60d31bf5ec42d.png,None,None,None,None,None,0
6,29,51,individual,Sharon's Millinery,"Bonamousadi, Douala",2021-06-16 19:36:44,2022-06-15 16:39:27,sharons-millinery.buyam.cm,NaN,None,None,None,None,None,None,None,0
7,30,52,business,HARD PRO,"AVENUE KENNEDY , FACE MAISON ORANGE",2021-06-18 17:35:16,2022-06-15 16:39:27,hardpro.buyam.cm,NaN,None,60d3146848e64.png,https://m.facebook.com/TheEverMoreIntelligentW...,None,https://instagram.com/hardpro237?utm_medium=co...,None,None,0
8,31,56,business,ETS TWS,"Avenue Kennedy, Face Maison Orange",2021-06-18 19:03:44,2022-06-15 16:39:27,tws.buyam.cm,NaN,None,60d9ff7890601.png,None,None,None,None,None,0
9,32,62,business,LA MAISON DE LAYETTES,"Acasia, En face du Restuarant Le Mendjang",2021-06-21 18:46:09,2022-06-15 16:39:27,lamaisondelayettes.buyam.cm,NaN,None,None,https://www.facebook.com/blueempireholdings/ab...,None,None,None,None,0

In [17]:
df3.head(10)

,id,user_id,name,name_fr,category_id,currency,price,hash,image,image_original,...,search_index,country,latitude,longitude,brand_id,created_at,updated_at,whole_sale,deleted_at,sellam_id
0,39,26,iphone 7,None,7,XAF,95000,None,60c1b2fd8c974.png,60c1b2fd8c974.png,...,iphone 7 iphone 7\r\n32GB\r\nFairly used but w...,237,3.88784,11.51661,NaN,2021-06-10 10:36:45,2021-07-29 15:50:50,0,NaT,0
1,40,26,iphone 7,None,7,XAF,95000,None,60c1b2fda51f3.png,60c1b2fda51f3.png,...,iphone 7 iphone 7\r\n32GB\r\nFairly used but w...,237,3.88784,11.51661,NaN,2021-06-10 10:36:45,2021-07-29 15:50:50,0,NaT,0
2,41,26,"COUCH, SIDE SOFAS, SOFA SETS",None,18,XAF,150000,None,60c40e46b9675.png,60c40e46b9675.png,...,"COUCH, SIDE SOFAS, SOFA SETS A spot to sit wit...",237,3.88784,11.51661,NaN,2021-06-12 05:30:46,2021-07-29 15:50:50,0,NaT,0
3,42,26,5 place Sofa,None,18,XAF,433000,None,60c40f63f3eb3.png,60c40f63f3eb3.png,...,5 place Sofa This 3 seat couch and a 2 seat c...,237,3.88784,11.51661,NaN,2021-06-12 05:35:31,2021-07-29 15:50:50,0,NaT,0
4,43,26,Titan TV Stand,None,18,XAF,102000,None,60c411366a838.png,60c411366a838.png,...,Titan TV Stand We like the rustic look of this...,237,3.88784,11.51661,NaN,2021-06-12 05:43:18,2021-07-29 15:50:50,0,NaT,0
5,44,26,TV Cabinet,None,18,XAF,163000,None,60c4139f832ee.png,60c4139f832ee.png,...,TV Cabinet This light brown TV cabinet brings ...,237,3.88784,11.51661,NaN,2021-06-12 05:53:35,2021-07-29 15:50:50,0,NaT,0
6,46,26,Macbook pro 13 2019,None,8,XAF,850000,None,60c41829345a8.png,60c41829345a8.png,...,Macbook pro 13 2019 Condition:\t\r\nUsed: An i...,237,3.88784,11.51661,NaN,2021-06-12 06:12:57,2021-07-29 15:50:50,0,NaT,0
7,47,26,Bed Cover,None,19,XAF,25000,None,60c423138d4af.png,60c423138d4af.png,...,Bed Cover This comprises a pair of pillow case...,237,3.88784,11.51661,NaN,2021-06-12 06:59:31,2021-07-29 15:50:50,0,NaT,0
8,48,26,Dual Color Bed Sheet LI-E02,None,19,XAF,40000,None,60c4242f4df96.png,60c4242f4df96.png,...,Dual Color Bed Sheet LI-E02 This set blue and ...,237,3.88784,11.51661,NaN,2021-06-12 07:04:15,2021-07-29 15:50:50,0,NaT,0
9,49,26,Bed PACK,None,19,XAF,292000,None,60c427898454b.png,60c427898454b.png,...,"Bed PACK This pack includes a headboard, a win...",237,3.88784,11.51661,NaN,2021-06-12 07:18:33,2021-07-29 15:50:50,0,NaT,0

In [19]:
df4= get_table_data("product_view_logs")
df5 = get_table_data("users")

Successfully connected to the database
Connection closed
Successfully connected to the database
Connection closed

In [27]:
df4.head(50) # product_view_logs

,id,user_id,product_id,user_lat,user_long,phone_metadata,user_phone_number,created_at,updated_at
0,1,292,851,NaN,NaN,None,+237651865148,2021-10-28 08:34:25,2021-10-28 08:34:25
1,2,292,552,NaN,NaN,None,+237651865148,2021-10-28 08:34:43,2021-10-28 08:34:43
2,3,292,914,NaN,NaN,None,+237651865148,2021-10-28 08:42:03,2021-10-28 08:42:03
3,4,292,287,NaN,NaN,None,+237651865148,2021-10-28 08:42:22,2021-10-28 08:42:22
4,5,292,182,NaN,NaN,None,+237651865148,2021-10-28 08:42:36,2021-10-28 08:42:36
5,6,292,183,NaN,NaN,None,+237651865148,2021-10-28 08:42:44,2021-10-28 08:42:44
6,7,292,286,NaN,NaN,None,+237651865148,2021-10-28 08:42:58,2021-10-28 08:42:58
7,8,292,42,NaN,NaN,None,+237651865148,2021-10-28 08:43:07,2021-10-28 08:43:07
8,9,292,287,NaN,NaN,None,+237651865148,2021-10-28 08:43:15,2021-10-28 08:43:15
9,10,292,182,NaN,NaN,None,+237651865148,2021-10-28 08:44:10,2021-10-28 08:44:10
10,11,292,467,NaN,NaN,None,+237651865148,2021-10-28 08:47:32,2021-10-28 08:47:32
11,12,292,464,NaN,NaN,None,+237651865148,2021-10-28 08:48:03,2021-10-28 08:48:03
12,13,115,930,NaN,NaN,None,237650628474,2021-10-28 09:34:17,2021-10-28 09:34:17
13,14,115,39,NaN,NaN,None,237650628474,2021-10-28 09:34:27,2021-10-28 09:34:27
14,15,115,67,NaN,NaN,None,237650628474,2021-10-28 09:35:52,2021-10-28 09:35:52
15,16,115,67,NaN,NaN,None,237650628474,2021-10-28 09:35:52,2021-10-28 09:35:52
16,17,0,620,NaN,NaN,None,,2021-10-28 10:39:09,2021-10-28 10:39:09
17,18,2766,733,NaN,NaN,None,237682819345,2021-10-28 11:18:57,2021-10-28 11:18:57
18,19,273,705,NaN,NaN,None,+237679821120,2021-10-28 11:36:56,2021-10-28 11:36:56
19,20,273,707,NaN,NaN,None,+237679821120,2021-10-28 11:37:38,2021-10-28 11:37:38
20,21,273,733,NaN,NaN,None,+237679821120,2021-10-28 11:37:56,2021-10-28 11:37:56
21,22,273,733,NaN,NaN,None,+237679821120,2021-10-28 11:43:05,2021-10-28 11:43:05
22,23,273,733,NaN,NaN,None,+237679821120,2021-10-28 12:22:31,2021-10-28 12:22:31
23,24,273,733,NaN,NaN,None,+237679821120,2021-10-28 12:26:31,2021-10-28 12:26:31
24,25,273,733,NaN,NaN,None,+237679821120,2021-10-28 12:37:38,2021-10-28 12:37:38
25,26,273,733,NaN,NaN,None,+237679821120,2021-10-28 12:40:49,2021-10-28 12:40:49
26,27,0,207,NaN,NaN,None,,2021-10-28 13:11:20,2021-10-28 13:11:20
27,28,0,109,NaN,NaN,None,,2021-10-28 13:11:43,2021-10-28 13:11:43
28,29,2794,926,NaN,NaN,None,237670041811,2021-10-28 14:15:57,2021-10-28 14:15:57
29,30,2196,931,NaN,NaN,None,237671586894,2021-10-28 14:28:14,2021-10-28 14:28:14
30,31,0,915,NaN,NaN,None,,2021-10-28 14:43:39,2021-10-28 14:43:39
31,32,0,387,NaN,NaN,None,,2021-10-28 14:43:55,2021-10-28 14:43:55
32,33,0,931,NaN,NaN,None,,2021-10-28 14:44:12,2021-10-28 14:44:12
33,34,0,934,NaN,NaN,None,,2021-10-28 14:44:24,2021-10-28 14:44:24
34,35,0,934,NaN,NaN,None,,2021-10-28 14:44:40,2021-10-28 14:44:40
35,36,0,933,NaN,NaN,None,,2021-10-28 14:44:54,2021-10-28 14:44:54
36,37,0,852,NaN,NaN,None,,2021-10-28 14:46:11,2021-10-28 14:46:11
37,38,0,931,NaN,NaN,None,,2021-10-28 14:46:55,2021-10-28 14:46:55
38,39,0,39,NaN,NaN,None,,2021-10-28 14:47:00,2021-10-28 14:47:00
39,40,0,592,4.19392,9.070953,Google Android SDK built for x86,,2021-10-28 15:09:20,2021-10-28 15:09:20
40,41,0,592,4.19392,9.070953,Google Android SDK built for x86,,2021-10-28 15:09:25,2021-10-28 15:09:25
41,42,2797,775,NaN,NaN,None,1(319) 343-8491,2021-10-28 15:11:49,2021-10-28 15:11:49
42,43,0,552,0.00000,0.000000,Itel W6002,,2021-10-28 15:54:07,2021-10-28 15:54:07
43,44,0,497,0.00000,0.000000,Itel W6002,,2021-10-28 15:54:16,2021-10-28 15:54:16
44,45,0,642,0.00000,0.000000,Itel W6002,,2021-10-28 15:58:48,2021-10-28 15:58:48
45,46,0,646,0.00000,0.000000,Itel W6002,,2021-10-28 15:58:58,2021-10-28 15:58:58
46,47,0,931,NaN,NaN,None,,2021-10-28 16:00:54,2021-10-28 16:00:54
47,48,0,553,0.00000,0.000000,Itel W6002,,2021-10-28 16:03:05,2021-10-28 16:03:05
48,49,2729,931,NaN,NaN,None,237678295811,2021-10-28 16:04:21,2021-10-28 16:04:21
49,50,2800,812,NaN,NaN,None,237670000364,2021-10-28 16:09:46,2021-10-28 16:09:46

In [26]:
df5.head(50) #  users

,id,name,address,email,country,phone,image,image_thumb,image_medium,latitude,...,bio,bio_fr,email_verified_at,search_index,remember_token,created_at,updated_at,approved_at,approved_by,vendor_profile_stage
0,22,Massabe Lydiane,None,massabe283,None,237656873567,None,None,medium_,NaN,...,None,None,NaT,Massabe Lydiane 237656873567,None,2021-06-09 17:24:07,2021-06-25 18:01:12,NaT,NaN,0
1,24,Lydiane Electronice,None,lydiane@gmail.com,237,+237682463671,None,None,medium_,NaN,...,None,None,NaT,Lydiane Electronice +237682463671,None,2021-06-09 17:47:32,2021-06-25 18:01:12,NaT,NaN,0
2,26,Hitech Cameroon Sarl,Casino Bastos,manjongkelvin4@gmail.com,237,+237674376335,60c1b01701569.png,thumb_60c1b01701569.png,medium_60c1b01701569.png,3.887840,...,Hitech-cm is an online platform. That exist s...,None,2021-06-09 20:26:13,Hitech Cameroon Sarl Hitech-cm is an online pl...,None,2021-06-09 18:22:50,2023-09-12 10:33:08,NaT,NaN,0
3,30,kuemo michel,None,kuemich17@yahoo.fr,237,+237697594177,None,None,medium_,NaN,...,None,None,2021-06-14 13:58:56,kuemo michel +237697594177,None,2021-06-14 13:57:41,2021-06-25 18:01:12,NaT,NaN,0
4,31,karim prada,None,karim.prada@yahoo.fr,237,+237674235399,None,None,medium_,NaN,...,None,None,NaT,karim prada +237674235399,None,2021-06-14 14:50:02,2021-06-25 18:01:12,NaT,NaN,0
5,33,Le Padré,"orange kennedy, Yaoundé",worldinfotel@gmail.com,237,+237697252756,61c07529a52e7.png,None,medium_,3.865140,...,Le Padre \r\n\r\nTon fournisseur agréé des pro...,None,2021-06-14 15:02:53,Le Padre Le Padre \r\n\r\nTon fournisseur agré...,None,2021-06-14 14:54:11,2021-12-20 17:23:35,NaT,NaN,0
6,37,Sarkozy Electronique,"En Face Orange Avenue Kennedy, Yaounde",egboifeanyi@gmail.com,237,+237696849569,635180b58917a.png,None,medium_,3.864970,...,"Sale of Smartphones \r\n\r\nSamsung, iPhone, ...",None,2022-10-20 17:05:10,Sarkozy Electronique Sale of Smartphones \r\n\...,None,2021-06-14 17:53:26,2022-10-20 17:32:56,2022-10-20,2898.0,0
7,38,Mbilla Michel,None,delpydus@yahoo.fr,237,+237698570096,None,None,medium_,NaN,...,None,None,NaT,Mbilla Michel +237698570096,None,2021-06-14 18:10:47,2021-06-25 18:01:12,NaT,NaN,0
8,39,CGI CAMEROUN,"576 Route de MELEN, BP 30181 YAOUNDE",armel.kamche@cgi-cameroun.com,237,+237670363030,60c7827e1bdcd.png,thumb_60c7827e1bdcd.png,medium_60c7827e1bdcd.png,3.863078,...,WE BUILD YOUR HOUSE AND YOU BUY IF YOU ARE SAT...,None,2021-06-14 19:42:47,CGI CAMEROUN WE BUILD YOUR HOUSE AND YOU BUY I...,None,2021-06-14 19:38:55,2021-11-08 15:10:08,NaT,NaN,0
9,40,AHMADOU SALI MODIBBO,None,contact@amsolutions.cm,237,+237696282843,None,None,medium_,NaN,...,None,None,NaT,AHMADOU SALI MODIBBO +237696282843,None,2021-06-15 10:04:10,2021-06-25 18:01:12,NaT,NaN,0
10,41,Ngeh eric langdji,None,ngeheric49@gmail.com,237,+237677832074,None,None,medium_,NaN,...,None,None,NaT,Ngeh eric langdji +237677832074,None,2021-06-15 14:55:56,2021-06-25 18:01:12,NaT,NaN,0
11,42,Tour Jumelle,"Douala, Kotto...Mbangue ,Toiture Rouge",tourjumelle@yahoo.com,237,+237652981954,60c9e5594494b.png,thumb_60c9e5594494b.png,medium_60c9e5594494b.png,4.105140,...,Tour Jumelle est un Etablissement d'hébergemen...,None,2021-06-15 15:10:35,Tour Jumelle Tour Jumelle est un Etablissement...,None,2021-06-15 15:07:28,2022-05-01 13:57:55,NaT,NaN,0
12,44,Glenn,Dirty South,glenn@gmail.com,237,+237672627247,62b82c189bb3f.png,thumb_60c9de19acb98.png,medium_60c9de19acb98.png,4.009535,...,None,None,2021-06-16 15:15:47,Fashion Dirty South +237672627247,None,2021-06-16 14:39:59,2023-06-13 14:42:07,NaT,NaN,0
13,50,Lawal Center,"Avenue Kennedy, face maison orange",lawalcenter1@gmail.com,237,+237690092024,60ca0cf3c4a8a.png,thumb_60ca0cf3c4a8a.png,medium_60ca0cf3c4a8a.png,3.865100,...,Lawal Center is a renounced shop that sells or...,None,2021-06-16 17:19:01,Lawal Center Lawal Center is a renounced shop ...,None,2021-06-16 17:17:51,2022-07-04 10:20:29,NaT,NaN,0
14,51,Sharon's Millinery,"Bonamousadi, Douala",mbengmpey@gmail.com,237,+237670209952,60ca1a8c96882.png,thumb_60ca1a8c96882.png,medium_60ca1a8c96882.png,4.076630,...,"Dealer In Hair Accessories, Fascinator , Hatin...",None,2021-06-16 17:27:55,"Sharon's Millinery Dealer In Hair Accessories,...",None,2021-06-16 17:25:26,2021-06-25 18:01:12,NaT,NaN,0
15,52,HARD PRO,"AVENUE KENNEDY , FACE MAISON ORANGE",mrstheque@yahoo.fr,237,+237674050509,60cca114c6409.png,thumb_60cca114c6409.png,medium_60cca114c6409.png,3.888710,...,Hardpro est une boutique d’appareils informati...,None,2021-06-16 19:45:28,HARD PRO Hardpro est une boutique d’appareils ...,None,2021-06-16 19:44:37,2021-06-25 18:01:12,NaT,NaN,0
16,56,ETS TWS,"Avenue Kennedy, Face Maison Orange",ttatchumwabo@yahoo.fr,237,+237697982757,60ccb5d043f97.png,thumb_60ccb5d043f97.png,medium_60ccb5d043f97.png,3.865220,...,"Specialistes en Electroniques, smartphone et o...",None,2021-06-18 16:15:20,"ETS TWS Specialistes en Electroniques, smartph...",None,2021-06-18 16:13:18,2021-06-25 18:01:12,NaT,NaN,0
17,60,Blue Empire Holdings LTD,"Molyko, opposite the presbyterian church",Blueempireholdingsltd@gmail.com,237,+237674884686,60d376a461c13.png,thumb_60d376a461c13.png,medium_60d376a461c13.png,4.156520,...,"In recent years, the Internet has been rife wi...",None,2021-06-21 11:21:05,"Blue Empire Holdings LTD In recent years, the ...",None,2021-06-21 11:18:52,2021-06-25 18:01:12,NaT,NaN,0
18,61,ABISE,"Maison Damase, Yaounde",artepie@yahoo.fr,237,+237699774940,60d62eb1eeb00.png,thumb_60d62eb1eeb00.png,medium_60d62eb1eeb00.png,3.823350,...,FUTURISTIC ART DECOR,None,2021-06-25 23:22:28,"ABISE FUTURISTIC ART DECOR Maison Damase, Yaou...",None,2021-06-21 11:31:09,2021-06-25 23:39:03,NaT,NaN,0
19,62,LA MAISON DE LAYETTES,"Acasia, En face du Restuarant Le Mendjang",yolandemekamgue@yahoo.fr,237,+237693794386,60d0a632b169a.png,thumb_60d0a632b169a.png,medium_60d0a632b169a.png,3.842620,...,layettes pour enfants,None,2021-06-21 18:26:17,LA MAISON DE LAYETTES layettes pour enfants Ac...,None,2021-06-21 18:24:40,2022-01-17 17:55:25,NaT,NaN,0
20,66,Sonfack,None,sonfack938,None,237652101243,None,None,medium_,NaN,...,None,None,NaT,Sonfack 237652101243,None,2021-06-22 19:39:15,2021-06-25 18:01:12,NaT,NaN,0
21,71,Mass Global Services,"Awae, Yaounde",massglobalservices@gmail.com,237,+237696853773,60d6a71121187.png,None,medium_,3.828910,...,Mass Global Services\r\n\r\n1) GPS/Security\r\...,None,2021-06-23 11:43:06,Mass Global Services Mass Global Services\r\n\...,None,2021-06-23 11:12:24,2021-06-26 08:06:17,NaT,NaN,0
22,73,Beauty Bliss,"TKC, Yaounde",lexzypaola22@gmail.com,237,+237650240818,60d64fab29287.png,None,medium_,3.823350,...,Your favorite hair stylist and dresser,None,2021-06-24 01:37:20,Beauty Bliss Your favorite hair stylist and dr...,None,2021-06-23 12:10:23,2021-06-26 08:05:22,NaT,NaN,0
23,75,ROMARIO BUSINESS,Avenue Kennedy,romariodassi@yahoo.fr,237,+237691170707,60d365b5b3f7a.png,thumb_60d365b5b3f7a.png,medium_60d365b5b3f7a.png,3.864750,...,Votre Partenaire Pour vos appareils électroniq...,None,2021-06-23 19:59:46,ROMARIO BUSINESS Votre Partenaire Pour vos app...,None,2021-06-23 19:53:22,2021-06-25 18:01:12,NaT,NaN,0
24,76,LE Concept,Carrefour Nsam-Escale en face Entree Oxygene,abang_maurice@yahoo.fr,237,+237698135380,60d38e3303e93.png,thumb_60d38e3303e93.png,medium_60d38e3303e93.png,3.820330,...,Le Concept \r\n\r\nNous offrons les services s...,None,2021-06-23 20:04:42,LE Concept Le Concept \r\n\r\nNous offrons les...,None,2021-06-23 19:53:33,2021-06-25 18:01:12,NaT,NaN,0
25,79,Ndasi Sylvain Rex Nzoye,None,ndasi629,None,237678034412,None,thumb_,medium_,NaN,...,None,None,NaT,Ndasi Sylvain Rex Nzoye 237678034412,None,2021-06-24 02:41:05,2021-06-25 18:01:12,NaT,NaN,0
26,80,Mballa Mbassi Narcisse Olivier,None,mballanarcisse959@gmail.com,237,+237698549390,None,None,None,NaN,...,None,None,2021-06-24 16:01:59,Mballa Mbassi Narcisse Olivier +237698549390,None,2021-06-24 15:58:20,2021-06-25 18:01:12,NaT,NaN,0
27,82,fernanda Hobdi,None,fernanda68,None,237697600241,None,None,None,NaN,...,None,None,NaT,fernanda Hobdi 237697600241,None,2021-06-25 17:43:10,2021-06-25 18:01:12,NaT,NaN,0
28,83,Paule,None,paule421,None,237693419744,None,None,None,NaN,...,None,None,NaT,None,None,2021-06-25 18:37:00,2021-06-25 18:37:00,NaT,NaN,0
29,85,Che Rachel Akweh,None,che594,None,237670013172,None,None,None,NaN,...,None,None,NaT,None,None,2021-06-26 02:05:27,2021-06-26 02:05:27,NaT,NaN,0
30,86,tonya michael,None,tonya10,None,237680405212,None,None,None,NaN,...,None,None,NaT,None,None,2021-06-26 19:38:29,2021-06-26 19:38:29,NaT,NaN,0
31,87,Tasia Store,"Simbock , Yaounde",jadecindyhoumouni@yahoo.fr,237,+237699843283,60d7562d9fb20.png,None,None,3.817300,...,"Get Your Good quality clothes , shoes and acce...",None,2021-06-26 20:22:03,"Tasia Store Get Your Good quality clothes , sh...",None,2021-06-26 20:16:23,2023-06-14 11:43:36,NaT,NaN,0
32,88,Manjong Kelvin,None,manjong543,None,237679854638,None,None,None,NaN,...,None,None,NaT,None,None,2021-06-26 23:43:14,2021-06-26 23:43:14,NaT,NaN,0
33,89,Lendzemo Lesley Jaidzeka,None,lendzemo797,None,237670861112,None,None,None,NaN,...,None,None,NaT,None,None,2021-06-27 18:08:07,2021-06-27 18:08:07,NaT,NaN,0
34,90,QUEENS VINTAGE,"Odza ,Yaounde",sophiemindjouli@yahoo.com,237,+237690042204,60dc1dab2bf72.png,None,None,3.804764,...,an online store that sells branded shoes and c...,None,2021-06-28 01:21:38,QUEENS VINTAGE an online store that sells bran...,None,2021-06-28 01:17:17,2021-07-01 12:35:57,NaT,NaN,0
35,92,EMELI MASANGO LISONGWE MARION,None,emelymarion2011@gmail.com,237,+237674808205,None,None,None,NaN,...,None,None,NaT,None,None,2021-06-29 02:47:35,2021-06-29 02:47:35,NaT,NaN,0
36,93,Funwi Glennfritz,None,gnhsglenn@gmail.com,237,+237680405112,None,None,None,NaN,...,None,None,NaT,None,None,2021-06-29 12:25:03,2021-06-29 12:25:03,NaT,NaN,0
37,94,Regy,"Cameroon, Douala",mr.hennessy23@gmail.com,237,+237670010399,60db47cae0ce8.png,None,None,NaN,...,We sell premium detox for health lovers,None,2021-06-29 20:13:44,Regy detox We sell premium detox for health lo...,None,2021-06-29 20:12:33,2021-06-29 22:35:19,NaT,NaN,0
38,95,Jaey Zeus,None,jaey441,None,237678488336,None,None,None,NaN,...,None,None,NaT,None,None,2021-06-30 00:53:13,2021-06-30 00:53:13,NaT,NaN,0
39,96,Jerome Sema,None,semajerome060@gmail.com,237,+237678488336,None,None,None,NaN,...,None,None,NaT,None,None,2021-06-30 00:56:16,2021-06-30 00:56:16,NaT,NaN,0
40,97,Lang Nestor Tem,None,lang44,None,237670173115,None,None,None,NaN,...,None,None,NaT,None,None,2021-06-30 00:56:56,2021-06-30 00:56:56,NaT,NaN,0
41,99,tchuomguem youmbi épouse TATCHUM Yvette,None,tchuomguem103,None,237676765999,None,None,None,NaN,...,None,None,NaT,None,None,2021-06-30 01:49:14,2021-06-30 01:49:14,NaT,NaN,0
42,100,Tchuomguem youmbi épouse TATCHUM Yvette,None,yvettetatchum79@gmail.com,237,+237676765999,None,None,None,NaN,...,None,None,NaT,None,None,2021-06-30 02:01:36,2021-06-30 02:01:36,NaT,NaN,0
43,101,Yuven Larry,None,yuven255,None,237677548508,None,None,None,NaN,...,None,None,NaT,None,None,2021-06-30 07:45:20,2021-06-30 07:45:20,NaT,NaN,0
44,102,YVY Pastries,"Mbankolo, Yaounde",yvybihmanjong21@gmail.com,237,+237682062253,60dc25c2e0c86.png,None,None,3.902150,...,YVY PASTRIES is your home pastry solution.\r\n...,None,2021-06-30 11:41:21,YVY PASTRIES YVY PASTRIES is your home pastry ...,None,2021-06-30 11:39:39,2021-06-30 12:06:53,NaT,NaN,0
45,103,237 CLOSET,Douala,sollizdjiffacj@gmail.com,237,+237681920552,60de292d45e31.png,None,None,4.101780,...,"Be style , be you",None,2021-06-30 12:44:45,"URBAN CLOSET Be style , be you Douala +2376819...",None,2021-06-30 12:39:43,2021-07-02 03:08:21,NaT,NaN,0
46,104,Njobam Elvist,None,njobam716,None,237670878550,None,None,None,NaN,...,None,None,NaT,None,None,2021-06-30 12:44:44,2021-06-30 12:44:44,NaT,NaN,0
47,105,Julie Paule,None,julie930,None,237661345309,None,None,None,NaN,...,None,None,NaT,None,None,2021-06-30 13:38:17,2021-06-30 13:38:17,NaT,NaN,0
48,106,anurin nwunembom,None,anurin227,None,237677854181,None,None,None,NaN,...,None,None,NaT,None,None,2021-06-30 16:19:50,2021-06-30 16:19:50,NaT,NaN,0
49,107,KONI SAM,None,doctokoni@yahoo.com,237,+237674294523,None,None,None,NaN,...,None,None,2021-06-30 17:06:31,None,None,2021-06-30 16:28:06,2021-06-30 17:06:31,NaT,NaN,0